# -*- coding: utf-8 -*-
"""app_final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqLGnZH2uYYvYSGzOlN5DoDjvWnlm8a0
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_parquet("career_data.parquet")
st.title("Career Earnings Analysis")

major_choice = st.selectbox("Pick a Major Category to view:", df['Major Category'].unique())

filtered_df = df[df['Major Category'] == major_choice]

# Plot 1
st.subheader(f"Income Distribution: {major_choice}")
fig1, ax1 = plt.subplots(figsize=(10, 6))
sns.histplot(filtered_df['INCWAGE'], bins=50, kde=True, color='skyblue', ax=ax1)
ax1.set_title(f'Distribution of Annual Income (INCWAGE)')
ax1.set_xlim(0, df['INCWAGE'].quantile(0.99)) # Using the 99th percentile limit they used
st.pyplot(fig1)

# Plot 2
st.subheader("Income by Education Level")
fig2, ax2 = plt.subplots(figsize=(14, 8))
sns.boxplot(x='INCWAGE', y='EducLabel', data=filtered_df.dropna(subset=['EducLabel']), palette='coolwarm', ax=ax2)
ax2.set_title('Annual Income Distribution by Education Level')
ax2.set_xlim(0, df['INCWAGE'].quantile(0.95))
st.pyplot(fig2)

st.write("### Data Preview")
st.dataframe(filtered_df.head())
